export const addedCommentErrors = {
  NOT_CONTAIN_NEEDED_PROPERTY: 'ADDED_COMMENT.NOT_CONTAIN_NEEDED_PROPERTY',
  NOT_MEET_DATA_TYPE_SPECIFICATION: 'ADDED_COMMENT.NOT_MEET_DATA_TYPE_SPECIFICATION',
};
