export const commentDetailErrors = {
  NOT_CONTAIN_NEEDED_PROPERTY: 'COMMENT_DETAIL.NOT_CONTAIN_NEEDED_PROPERTY',
  NOT_MEET_DATA_TYPE_SPECIFICATION: 'COMMENT_DETAIL.NOT_MEET_DATA_TYPE_SPECIFICATION',
};
