version: '3'
services:
  nginx:
    image: muktiarafi/forum-nginx
    ports:
      - '80:80'

  app:
    image: muktiarafi/forum-api
    env_file:
      - .env

  # use database container instead of rds for now
  pg:
    image: postgres:alpine
    env_file:
      - .env
