export const registerUserErrors = {
  NOT_CONTAIN_NEEDED_PROPERTY: 'REGISTER_USER.NOT_CONTAIN_NEEDED_PROPERTY',
  NOT_MEET_DATA_TYPE_SPECIFICATION: 'REGISTER_USER.NOT_MEET_DATA_TYPE_SPECIFICATION',
  USERNAME_LIMIT_CHAR: 'REGISTER_USER.USERNAME_LIMIT_CHAR',
  USERNAME_CONTAIN_RESTRICTED_CHARACTER: 'REGISTER_USER.USERNAME_CONTAIN_RESTRICTED_CHARACTER',
};
