export const registeredUserErrors = {
  NOT_CONTAIN_NEEDED_PROPERTY: 'REGISTERED_USER.NOT_CONTAIN_NEEDED_PROPERTY',
  NOT_MEET_DATA_TYPE_SPECIFICATION: 'REGISTERED_USER.NOT_MEET_DATA_TYPE_SPECIFICATION',
};
