export const logoutUseCaseErrors = {
  NOT_CONTAIN_REFRESH_TOKEN: 'LOGOUT_USER_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN',
  PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION: 'LOGOUT_USER_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION',
};
