export const refreshAuthUseCaseErrors = {
  NOT_CONTAIN_REFRESH_TOKEN: 'REFRESH_AUTHENTICATION_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN',
  PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION: 'REFRESH_AUTHENTICATION_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION',
};
