export const threadDetailErrors = {
  NOT_CONTAIN_NEEDED_PROPERTY: 'THREAD_DETAIL.NOT_CONTAIN_NEEDED_PROPERTY',
  NOT_MEET_DATA_TYPE_SPECIFICATION: 'THREAD_DETAIL.NOT_MEET_DATA_TYPE_SPECIFICATION',
};
