name: CD
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/forum-api
      NGINX_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/forum-nginx
    steps:

    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build image
      run: |
        docker build -t $APP_IMAGE .
        docker build -t $NGINX_IMAGE ./nginx
        
    - name: Push to Docker Hub
      run: |
        docker push $APP_IMAGE
        docker push $NGINX_IMAGE

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' 'terraform/*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: forum
        environment_name: forum-env
        region: ap-southeast-1
        version_label: '1'
        deployment_package: deploy.zip
